name = "voice-flow"
main = "src/index.ts"
compatibility_date = "2024-04-01"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "voice-flow-db"
database_id = "P9IovFUgOVrhS2ylsMfXKJ1saqbr8TxO"

[vars]

LARK_VERIFICATION_TOKEN = "P9IovFUgOVrhS2ylsMfXKJ1saqbr8TxO"


